FROM python:3.10-slim

# Checkout and install dagster libraries needed to run the gRPC server
# exposing your repository to dagster-webserver and dagster-daemon, and to load the DagsterInstance

WORKDIR /opt/dagster/app

COPY . /opt/dagster/app

RUN apt update && apt install -y libpq-dev && rm -rf /var/lib/apt/lists/*
RUN pip install -r requirements.txt
RUN pip install .

# Run dagster gRPC server on port 4000

EXPOSE 4000

# CMD allows this to be overridden from run launchers or executors that want
# to run other commands against your repository
CMD ["dagster", "api", "grpc", "-h", "0.0.0.0", "-p", "4000", "--package-name", "scooters"]
